import { useRef } from 'react';
import { Hero, SectionHead, useReveal } from '../components/Editorial';
import '@/styles/about.css';

const UPDATED = '5 October 2026';

/** Plain-language privacy and terms. Keep this true: update it whenever data handling changes. */
export default function Privacy() {
  const root = useRef<HTMLDivElement>(null);
  useReveal(root);
  return (
    <div className="ed-page privacy" ref={root}>
      <Hero back compact kicker="Privacy & terms" title="Your data," accent="plainly." lead={`What Utopia stores, what it sends, and what it never does. Last updated ${UPDATED}.`} />

      <section className="ab-section">
        <SectionHead eyebrow="Short version" title="Five things to know" />
        <ol className="privacy-list" data-reveal>
          <li>
            <b>No account, no sign-up.</b> We don’t ask for your name, email or phone number.
          </li>
          <li>
            <b>Your progress lives on your device</b> (scores, stars, orbs, settings). You can export, import or delete it any time in Settings.
          </li>
          <li>
            <b>Anonymous usage stats</b> help us see which games people enjoy and come back to. They use a random ID, no cookies, and you can switch them off in Settings. Your browser’s “Do Not Track” is honoured.
          </li>
          <li>
            <b>Voice games:</b> the game’s voice is generated by Sarvam AI. If you choose to answer by microphone, the recording is sent to Sarvam AI to be turned into text and is not stored by Utopia. You can always type instead.
          </li>
          <li>
            <b>No forced ads, nothing to buy with real money,</b> and no selling of your data.
          </li>
        </ol>
      </section>

      <section className="ab-section privacy-body">
        <SectionHead eyebrow="The details" title="What, where and why" />
        <div data-reveal>
          <h3>On your device</h3>
          <p>
            Utopia saves game progress, history, rewards (orbs, stars, cosmetics) and your settings in your browser’s local storage. It never leaves your device unless you export it yourself. Clearing your browser data, or (on iPhone) not visiting for 7 days without adding Utopia to your Home Screen, can erase it.
          </p>
          <h3>Anonymous analytics (PostHog)</h3>
          <p>
            If analytics is on, we send events like “app opened”, “game started/finished”, scores, durations and which settings were changed, with a random device ID. We don’t send names, emails, precise location, microphone audio or per-move gameplay. Turn it off in Settings → Data & privacy.
          </p>
          <h3>Voice (Sarvam AI)</h3>
          <p>
            Spoken prompts are produced by Sarvam AI’s text-to-speech and cached so the same phrase isn’t generated twice. Microphone answers are only recorded after you agree, only while a voice game is listening, and are sent to Sarvam AI for speech-to-text. Utopia keeps only the resulting text for scoring that round. Sarvam AI processes audio under its own terms.
          </p>
          <h3>Ads</h3>
          <p>
            Utopia doesn’t show ads unless you choose to watch one for an in-game reward. If rewarded ads are enabled, they are provided by Google and only load when you ask for one. Players under 18 should not receive personalised ads.
          </p>
          <h3>Children</h3>
          <p>
            Utopia doesn’t ask anyone for personal details. Schools and parents can turn off analytics in Settings before children play.
          </p>
          <h3>Not medical advice</h3>
          <p>
            The games are designed around abilities and inspired by published research. They are not a medical device, diagnosis or treatment, and we don’t claim they improve memory, attention or any condition.
          </p>
          <h3>Terms, briefly</h3>
          <p>
            Utopia is provided free, as is, for personal and classroom use. Orbs and cosmetics have no cash value and can’t be bought or sold. Please don’t misuse the voice service (for example automated requests). We may change or remove games over time.
          </p>
          <h3>Contact</h3>
          <p>
            Questions or deletion requests: use the feedback link in Settings, or open an issue at{' '}
            <a href="https://github.com/1sakshm/project-utopia" target="_blank" rel="noreferrer">
              github.com/1sakshm/project-utopia
            </a>
            .
          </p>
        </div>
      </section>
    </div>
  );
}
