import { useEffect, useRef } from 'react';
import type { Ability, GameManifest, GameModule } from '@/sdk/types';
import { ABILITY_LABEL, ringOf } from '@/platform/abilities';
import { usePosters } from '@/platform/posters';
import { createGameHost, type GameHost } from '@/runtime/host';
import { canRunLivePreview } from '@/runtime/quality';
import { useSettings } from '@/platform/settings';
import { hashString } from '@/sdk/rng';

export function AbilityChip({ ability }: { ability: Ability }) {
  const r = ringOf(ability);
  return (
    <span className="chip">
      <span className="chip-glyph" style={{ background: r.color }} aria-hidden>
        {r.glyph}
      </span>
      {ABILITY_LABEL[ability]}
    </span>
  );
}

/**
 * Poster: the frame captured from this device's last live preview if available, else the build-time
 * poster (public/posters/<id>.jpg, generated by scripts/capture-posters.mjs).
 */
export function PosterArt({ manifest, className }: { manifest: GameManifest; className?: string }) {
  const url = usePosters((s) => s.posters[manifest.id]);
  const p = manifest.palette;
  const h = hashString(manifest.id);
  const ax = 20 + (h % 60);
  const ay = 20 + ((h >>> 8) % 40);
  return (
    <div
      className={`poster ${className ?? ''}`}
      style={{
        backgroundColor: p.bg,
        // Runtime-captured frame, else the build-time poster, over palette gradients (shown if the image is missing).
        backgroundImage: `url(${url ?? `/posters/${manifest.id}.jpg`}),
             radial-gradient(60% 40% at ${ax}% ${ay}%, ${p.accent}55 0%, transparent 70%),
             radial-gradient(50% 35% at ${100 - ax}% ${ay + 35}%, ${p.accent2}44 0%, transparent 70%),
             linear-gradient(180deg, ${p.bg} 0%, ${p.bg2} 100%)`,
      }}
      aria-hidden
    />
  );
}

/**
 * Live preview surface. Mounts the game in preview (attract) mode while `active`,
 * pauses immediately when inactive and destroys shortly after (capturing a poster frame first).
 */
export function LivePreview({ module, active, variant = 'normal' }: { module: GameModule; active: boolean; variant?: 'normal' | 'daily' }) {
  const box = useRef<HTMLDivElement>(null);
  const host = useRef<GameHost | null>(null);
  const feedSound = useSettings((s) => s.feedSound);
  const previewStyle = useSettings((s) => s.previewStyle);
  const putPoster = usePosters((s) => s.put);

  useEffect(() => {
    if (!active || !box.current || !canRunLivePreview()) return;
    let captureTimer = 0;
    const el = box.current;
    const dwell = window.setTimeout(() => {
      const h = createGameHost(module, el, {
        mode: 'preview',
        variant,
        seed: hashString(module.manifest.id + variant),
        startLevel: 1,
        onError: (e) => console.warn(`[preview:${module.manifest.id}]`, e),
      });
      host.current = h;
      h.ready.then(() => {
        el.classList.add('is-live');
        captureTimer = window.setTimeout(() => {
          const url = h.capture();
          if (url) putPoster(module.manifest.id, url);
        }, 2500);
      });
    }, 250);
    return () => {
      window.clearTimeout(dwell);
      window.clearTimeout(captureTimer);
      const h = host.current;
      host.current = null;
      el.classList.remove('is-live');
      if (h) {
        h.pause();
        const url = h.capture();
        if (url) putPoster(module.manifest.id, url);
        h.destroy();
      }
    };
  }, [active, module, variant, putPoster, previewStyle]);

  useEffect(() => {
    host.current?.setMuted(!feedSound);
  }, [feedSound]);

  return <div ref={box} className="live-preview" aria-hidden />;
}

export function formatScore(n: number) {
  return n.toLocaleString();
}
